---
extends: "default"
ignore:
  - "/node_modules"
  - "/public"
rules:
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  quoted-strings:
    quote-type: "double"
    required: true
