export {
  IconAlertCircle as Incidents,
  IconBook2 as TragedySet,
  IconCalendar as Days,
  IconClipboard as Cheatsheet,
  IconFileDescription as Generate,
  IconFileTextSpark as PlotRules,
  IconTrophy as WinConditions,
  IconUfo as TraitorWinConditions,
  IconUserExclamation as RoleAbilities,
  IconUsers as Cast,
  IconUsers as Players,
  IconZoom as Mastermind,
  IconZoomScan as MastermindAbilities,
} from "@tabler/icons-react";
