---
name: "Test"
on:
  push:
    branches-ignore:
      - "main"
  workflow_call:
jobs:
  test:
    name: "Run unit tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "pnpm/action-setup/@v4"
        with:
          version: "latest"
      - uses: "actions/setup-node@v4"
        with:
          node-version: "lts/jod"
          cache: "pnpm"
      - name: "Install Dependencies"
        run: "pnpm install --frozen-lockfile"
      - name: "Build i18n"
        run: "pnpm build:i18n"
      - name: "Run unit tests"
        run: "pnpm test"
